/** Client hot-fix list when server sends too few password options (Crypto Hack). */
export const FALLBACK_CRYPTO_PASSWORD_OPTIONS: string[] = [
    "Bitcoin",
    "Ethereum",
    "Dogecoin",
    "Solana",
    "Cardano",
    "Ripple",
    "Binance",
    "Tether",
    "Polkadot",
    "Litecoin",
    "Chainlink",
    "Stellar",
    "Monero",
    "Tron",
    "Cosmos",
    "Tezos",
    "IOTA",
    "Neo",
    "Dash",
    "Zcash",
    "Maker",
    "Aave",
    "Uniswap",
    "Sushi",
    "Compound",
    "Curve",
    "Yearn",
    "Polygon",
    "Avalanche",
    "Terra",
    "Algorand",
    "VeChain",
    "Filecoin",
    "Sandbox",
    "Decentraland",
    "Axie",
    "Theta",
    "Fantom",
    "Quant",
    "Hedera",
    "Near",
    "Flow",
    "EOS",
    "TrueUSD",
    "Zilliqa",
    "Harmony",
    "Elrond",
    "Enjin",
    "Chiliz",
    "Kusama",
]

export function resolveCryptoPasswordOptions(serverOptions: string[]): string[] {
    return serverOptions.length < 10 ? [...FALLBACK_CRYPTO_PASSWORD_OPTIONS] : serverOptions
}
